### PR TITLE
Completion of all files doing something idk

### PR DESCRIPTION
**Pull request by vispin**
We should get this done by the end of this week because I'll be hammered by finals, and won't be able to help. We could also finish during summer but it's too hot to do anything.

### CODE REVIEW

**Comment by vispin** [comment]
Also, we should be fine considering that we're using Java 17, not Java 8. I believe that gdude said something about Java 8 being dropped because some features require a version that is newer. We could also bump our JVM to 18, but I kind of want to use an LTS, rather than the latest release, so we'll see how that goes.

**Comment by vispin** [comment]
We should be able to use MongoDB? We might need to switch to PostgreSQL because it is oracle, but theoretically this should work properly.
https://blogs.oracle.com/database/post/mongodb-api#:~:text=Customers%20can%20now%20run%20MongoDB,just%20change%20the%20connection%20string.

**Comment by shuuyu** [comment]
If you want to reimplement locales, I'm down to because it's easier to access in a way (Preferentially of course)

**Comment by shuuyu** [comment]
Why have you been resting smh

**Comment by vispin** [comment]
I mean, I can finish all of the commands today, it's just going to take awhile because we're using oracle dbs right?

**Pull request merged**
