### PR TITLE
DEV 1.0.0-PRE-1

### PR DESCRIPTION
**Pull request by shuuyu**
TODO: 
These are to be done as soon as when Nabi releases for public use.
The lower it is, the lower the priority is.

- [ ] Implementation of all commands (Including the Phishing ones)
- [ ] Finish all events
- [ ] Finish Database Implementation
- [ ] Affiliate server commands
- [ ] Add proper documentation of how to set up the bot
- [ ] Active Phishing implementation
- [x] Relicense the bot to be available for public usage (But they cannot use it for commercial purposes)
- [x] Two week period for when the bot does eventually release to the public
- [x] Stress test the server that we were given

OPTIONAL:
These aren't required for the official release, but it would be nice for this to be finished.

- [ ] Switch logging to Log4j2 or SLF4j, it doesn't really matter to be honest.
- [x] Switch to PostgreSQL because Oracle exists and it hates me. 
- [x] Add locales support (This might need to be in a separate repository because of how things are structured, we'll see how it goes)

All of this is primarily because I've been lazy for the first week, and haven't done anything. 

For the phishing API, I'm thinking of either using the one provided in [Zerotwo](https://anti-fish.bitflow.dev/) or [Google's own Safeguarding API](https://developers.google.com/safe-browsing). Either of which will work fine, I just want something that isn't restrictive in any capacity.

Documentation, as well as the website for Nabi, will go onto another site, because I don't like the idea of combining two ideas and then making a hack for it.

### CODE REVIEW

**Comment by shuuyu** [comment]
Remind me to never use Hybrid commands ever again because they're terrible
Message commands are terrible as well

**Comment by shuuyu** [comment]
Remind me to decrease the amount of boilerplate within the code, I might fix it tomorrow or some other release, but as of right now, we definitely need to reduce the amount of boilerplate in the code. Please get onto that you nerd

**Review by vispin — COMMENTED** [review]
You look like an idiot for including allprojects but whatever it works

**Review by vispin — APPROVED** [review]
ok you're bad

**Review by shuuyu — COMMENTED** [review]
Rewrite this because it for sure doesn't work properly

**Comment by shuuyu** [comment]
We're going to rewrite this bot soon so like all of this is useless now

**Pull request closed without merging**
