### PR TITLE
Fix gradle from not working lol

### LINKED ISSUE #4: Implementation of another phishing API instead of Kordex's own
This should provide improvements over trying to detect phishing links, as well as beneficial response times. We will continue to monitor if the Google's safeguarding API is functional, then implement it in 0.1.0 SNAPSHOT. This might take a while due to the implementations that we are going to use (i.e. another API to add to the dependency WOOOOOHOOOO)

### PR DESCRIPTION
**Pull request by vispin**
Prepping merge for official release (Whenever it happens)

### CODE REVIEW

**Comment by vispin** [comment]
We could also add Serenity to this if you want, considering you keep switching the language of Serenity every 10 seconds.

**Comment by vispin** [comment]
Also we might need to switch all main directories to jvmMain because of my funny

**Comment by vispin** [comment]
Oh right multiplatform breaks gradle, need to remove it

**Comment by vispin** [comment]
Also, we need to add ktor, but not 2.0.0 yet because apparently Kord doesn't work with it

**Review by shuuyu — APPROVED** [review]
Okay, I'll merge this when we fix this issue, as well as fix the circular dependency issue.
image

**Comment by shuuyu** [comment]
#9 Fixed already, forgot to close it

**Comment by shuuyu** [comment]
If you can fix that then we should be fine with the entire circular dependency issue tmr

**Comment by shuuyu** [comment]
Also I'm only locking this so no trolls get in the way of making some useless issues and spamming the webhook

**Comment by shuuyu** [comment]
Also this is a draft now until we fix the underlying issues because I decided to get lazy and not fix gradle so have fun at that

**Comment by shuuyu** [comment]
I fixed a bit of the issue, might push later if I finish a bit of this hw

**Comment by shuuyu** [comment]
Well I have hw so you can fix that soon ig

**Comment by vispin** [comment]
Why'd you push the same commit message twice lol

**Comment by vispin** [comment]
I mean, if you want to implement ktor right now, we can.

**Comment by shuuyu** [comment]
I mean, it works now, but we need to add everything back in, so it is going to make gradle cry again

**Comment by shuuyu** [comment]
Wait nvm

**Pull request merged**
